### ISSUE TITLE
Transformalize Task Scheduling

### ISSUE THREAD

**Issue by vlad2kgithub** [dalenewman/OrchardCore.Transformalize#13]
It would be handy to have the ability to schedule Transformalize Task.

**Comment by dalenewman** [comment]
Update to the latest version, then:

1. In Admin > Configuration > Features,  enable *Timer Workflow Activities*.
1. Create a new *Workflow Type*
1. Add a *Timer Event* and set it as the *Startup Task*.
1. Add a *Transformalize Task*.
1. Connect the *Done* output on the *Timer Event* to the *Transformalize Task*.

You provide the *Transformalize Task* with the alias of the one you want to run.  It will run it when the timer event tells it to.  Here's a [nice video](https://youtu.be/pi_WiSqp5x4) demonstrating workflow in Orchard Core.

![ScheduledTask](https://user-images.githubusercontent.com/933086/106985273-236adc00-6737-11eb-9075-8b86bbf3802b.PNG)
