### ISSUE TITLE
Task and Form Parameters Auto Complete Setting

### ISSUE THREAD

**Issue by vlad2kgithub** [dalenewman/OrchardCore.Transformalize#15]
It would be nice to have an auto-complete="true|false" in parameter - and then have the orchard module respect it, by adding property HTML attribute to form.

**Comment by dalenewman** [comment]
I implemented and tested it and it seems to have the desired affect on my PC.  The image dalenewman/transformalize.orchard is being published (it takes a few minutes).  So, to emphasize what I said in the commit, the default behavior is to not have autocomplete (off).  So, if you want it on parameters, you have to `AutoComplete="true"` it on the parameter.
