### ISSUE TITLE
Package not found.

### ISSUE THREAD

**Issue by hyzx86** [dalenewman/OrchardCore.Transformalize#22]
Hi ，I have change the nuget url to : `https://www.myget.org/F/transformalize/api/v3/index.json` 
but the package still not found.

Did I lost something?

![image](https://user-images.githubusercontent.com/15613121/121914919-49e3f800-cd65-11eb-8569-41411479143e.png)

**Comment by dalenewman** [comment]
You shouldn't have had to change anything, as the nuget package sources are defined in nuget.config, e.g.:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
   <packageSources>
      <clear />
      <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
      <add key="MyGet Transformalize" value="https://www.myget.org/F/transformalize/api/v3/index.json" />
   </packageSources>
   <disabledPackageSources />
</configuration>
```

I would expect that when you "build" the solution it would try to restore the packages.  I'm not sure what's wrong :-(

**Comment by hyzx86** [comment]
I think it may be the network problem of GFW. Do you plan to release to NUGET.ORG in the near future?



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 15, 2021 21:48 PM
To: ***@***.***&gt;;
Cc: "Tony ***@***.******@***.***&gt;;
Subject: Re: [dalenewman/OrchardCore.Transformalize] Package not found. (#22)




 
You shouldn't have had to change anything, as the nuget package sources are defined in nuget.config, e.g.:
 <?xml version="1.0" encoding="utf-8"?&gt; <configuration&gt;    <packageSources&gt;       <clear /&gt;       <add key="NuGet" value="https://api.nuget.org/v3/index.json" /&gt;       <add key="MyGet Transformalize" value="https://www.myget.org/F/transformalize/api/v3/index.json" /&gt;    </packageSources&gt;    <disabledPackageSources /&gt; </configuration&gt;
 
I would expect that when you "build" the solution it would try to restore the packages.  I'm not sure what's wrong :-(

**Comment by hyzx86** [comment]
It was indeed a network problem, which was solved by using a VPN, but it was not very convenient

![image](https://user-images.githubusercontent.com/15613121/122249483-77fb4080-cefb-11eb-8e1a-cdc7cef54172.png)
It would be great if we could use a pre-release version and post it to nuget.org
