### ISSUE TITLE
multilple and size

### ISSUE THREAD

**Issue by vlad2kgithub** [dalenewman/OrchardCore.Transformalize#4]
multilple and size and size are not implemented in OCT

**Comment by dalenewman** [comment]
You're using the field's shortcut attribute for parameters (i.e. `parameter="facet"`).  You don't get access to `multiple` and `size` when you do it that way.   You'll have to define the _parameter_ and the _filter_ yourself:

Define the parameter like this, and you can set `multiple` to true.

```xml
  <parameters>
     <add name="PremiseStreet" label="Street" value="*" prompt="true" multiple="true" />
  </parameters>
```

Define the filter inside the entity, and you can set size.

```xml
  <entities>
    <add name="x" label="y">
      <filter>
          <add field="PremiseStreet" value="@[PremiseStreet]" type="facet" size="500" /> 
      </filter>
      <fields/><!-- left out fields out for brevity -->
    </add>
  </entities>
```
