### ISSUE TITLE
Use as an importer for content items ?

### ISSUE THREAD

**Issue by giannik** [dalenewman/OrchardCore.Transformalize#5]
Hello,
I have a scenario where I have an excel file with data and want to import into orchard as content items.
For instance in excel I have 2 columns (Title , Content) and  records under these columns.
In Orchard core I have a contentype named Policy with a titlePart and a html body part.

Can I create a scenario with transformalize to get the data from the excel file (source)  and import into orchard (Target) as  Policy Content Items ? 

Orchard can already import content in json format (using the recipes feature) so I guess it would be enough for transformalize to convert into the correct json format and then use orchards recipe import feature to do the rest.

Is this possible with transformalize ?
Thanks.

**Comment by dalenewman** [comment]
It's not possible with this Orchard Core module.  

It might be possible using the command line [Transformalize](https://github.com/dalenewman/Transformalize) in combination with the [Excel](https://github.com/dalenewman/Transformalize.Provider.Excel) provider as input and the [Razor](https://github.com/dalenewman/Transformalize.Provider.Razor) provider as output.  You'd use a template to transform between the two.

It's not an ideal use case for transformalize.
