### ISSUE TITLE
Is it posssible to validate a record before posting the update ?

### ISSUE THREAD

**Issue by giannik** [dalenewman/OrchardCore.Transformalize#7]
I have a scenario to update lead records in an sql database from one marketing campaign to another.
But i have to check for specific business rules to each lead if it is eligible to move.
Business rules are if form of predicates (true/false) might be like : 
-   A lead with existing child records in table x cannot be updated.
-  A lead in status y cannot be updated .

Is it possible to express these rules and have the system notify me in the log the records that violate rules and cannot be updated ?

**Comment by dalenewman** [comment]
It is "possible" but, like a lot of things in this repository, it's pretty much undocumented.

If you really want to do this in Transformalize, Here are some things to look at:
- [tests](https://github.com/dalenewman/Transformalize/tree/master/src/Test.Unit.Shared/Validation)
- [built in validators](https://github.com/dalenewman/Transformalize/tree/master/Transformalize/Validators)
- [the most flexible validator (javascript)](https://github.com/dalenewman/Transformalize.Transform.Jint/blob/master/test/Test.Integration.Shared/TestValidator.cs)

Validators are operations (like Transforms are).  Transform short-hand is set in an attribute called `t` while validator short-hand is set in the `v` attribute.  Validators do not transform/modify anything.  They produce an indication of valid, and a message.  If you have a validator in a field called *Field1*, Transformalize will automatically make a bool field called *Field1Valid* and a string field called *Field1Message*.  You can set these fields explicitly in the field as well with `valid-field` and `message-field` but then you have to define those fields too (as calculated fields that are not input).

If I have time I'll will make an example.

But, once you've figured out validation in Transformalize, you will want to know the approach we use.  The approach to validating data *before you update it* somewhere else is this.  You have one arrangement do the validation and produce an output with record-level and/or field level indication of the records' validity, then you have a subsequent action (or another arrangement) query the output of the first arrangement (only selecting valid records) to be updated in your ultimate destination.

**Comment by giannik** [comment]
Hmm interesting. 
I will look at the pointers you mention.
Thanks.
