### ISSUE TITLE
Allow Forms to use Common Connections

### ISSUE THREAD

**Issue by vlad2kgithub** [dalenewman/OrchardCore.Transformalize#9]
The forms are not using common connections (when referenced).  They are only using explicit connections this leads to having to keep full connections (with credentials) in each form.

Can forms be made to use common connections?  In addition, can they re-use the common connections for different forms by allowing us to specify only the name, and table-name in the connection in the form?

Thanks

**Comment by dalenewman** [comment]
This is working now, e.g.

```xml
<connections>
   <add name="common-connection" table="form_table" />
</connections>
```

The *common-connection* refers to a connection you have setup in the Transformalize > Settings administration page.
